-- 모델러 계정 생성 테스트

alter session set "_ORACLE_SCRIPT"=true;

create user modeler1 identified by modeler1;

grant create session to modeler1;

grant connect, resource, DBA to modeler1;

alter user modeler1 default tablespace users quota unlimited on users;

-- MESFactoryList
CREATE TABLE MESFACTORY
(
    FACTORYNAME VARCHAR2(40)
);

ALTER TABLE MESFACTORY ADD CONSTRAINT MESFACTORY_pk PRIMARY KEY (FACTORYNAME);

COMMENT ON
TABLE MESFACTORY IS 'FACTORY';

COMMENT ON
COLUMN MESFACTORY.FACTORYNAME IS 'FACTORYNAME';


-- PROCESSFLOW
CREATE TABLE PROCESSFLOW
(
    FACTORYNAME VARCHAR2(40),
    PROCESSFLOWNAME VARCHAR2(40)
);

ALTER TABLE PROCESSFLOW ADD CONSTRAINT PROCESSFLOW_pk PRIMARY KEY (FACTORYNAME,PROCESSFLOWNAME);

COMMENT ON
TABLE PROCESSFLOW IS 'PROCESSFLOW';

COMMENT ON
COLUMN PROCESSFLOW.FACTORYNAME IS 'FACTORYNAME';

COMMENT ON
COLUMN PROCESSFLOW.PROCESSFLOWNAME IS 'PROCESSFLOWNAME';


-- PROCESSOPERATION
CREATE TABLE PROCESSOPERATION
(
    FACTORYNAME VARCHAR2(40),
    PROCESSOPERATIONNAME VARCHAR2(40)
);

ALTER TABLE PROCESSOPERATION ADD CONSTRAINT PROCESSOPERATION_pk PRIMARY KEY (FACTORYNAME,PROCESSOPERATIONNAME);

COMMENT ON
TABLE PROCESSOPERATION IS 'PROCESSOPERATION';

COMMENT ON
COLUMN PROCESSOPERATION.FACTORYNAME IS 'FACTORYNAME';

COMMENT ON
COLUMN PROCESSOPERATION.PROCESSOPERATIONNAME IS 'PROCESSOPERATIONNAME';